"""Stage127 — import and independent revalidation of the external TSETMC bundle.

The external delivery ``stage127_m2_tsetmc_full_delivery.zip`` is treated as
IMMUTABLE SOURCE EVIDENCE. This module never edits it: it opens the ZIP,
verifies its identity, and then re-derives every claim the external party made
from the raw evidence inside it.

The external QC flag is never trusted. Every number the Gate later relies on is
recomputed here from ``raw_restricted/`` and cross-checked against the delivered
normalized rows, and every check fails closed.

Nothing here computes a scientific feature, fits a model, or reads a final-test
row: the firewall is enforced structurally on the imported dates themselves.
"""
from __future__ import annotations

import csv
import hashlib
import io
import json
import os
import zipfile
from datetime import date
from typing import Any, Iterable

# --------------------------------------------------------------------------- #
# Identity of the authorized immutable delivery
# --------------------------------------------------------------------------- #

BUNDLE_FILENAME = "stage127_m2_tsetmc_full_delivery.zip"
BUNDLE_SHA256 = "d8456b50b7813b44789b556efcdd9ed81ee0318f85e3d9127b27807f75c6c6ec"
BUNDLE_SIZE_BYTES = 13_464_145

ROOT = "stage127_tsetmc_full"

#: SHA256 of the canonical request generated by PR #66. The delivery is only
#: admissible if it answered EXACTLY this ticker/range universe.
CANONICAL_REQUEST_SHA256 = (
    "4b9cfef4c3543abfcae1d3d660c9415ac3a83711dea1094998ea9c2bce5ef374"
)
CANONICAL_REQUEST_REL = (
    "project/stage127/external_retrieval/"
    "stage127_m2_external_retrieval_ticker_ranges.csv"
)

BUNDLE_REQUEST_REL = f"{ROOT}/input/stage127_m2_external_retrieval_ticker_ranges.csv"
BUNDLE_README_REL = f"{ROOT}/README.md"

OUT = f"{ROOT}/output"
DAILY_REL = f"{OUT}/stage127_m2_external_return_daily.csv"
MAPPING_REL = f"{OUT}/stage127_m2_external_return_mapping.csv"
MANIFEST_REL = f"{OUT}/stage127_m2_external_return_manifest.csv"
STATUS_AUDIT_REL = f"{OUT}/full_retrieval_status_audit.csv"
RAW_SHA_MANIFEST_REL = f"{OUT}/raw_sha256_manifest.csv"
PROVENANCE_REL = f"{OUT}/restricted_raw_provenance_manifest.csv"
EXTERNAL_QC_REL = f"{OUT}/full_extraction_qc_report.json"

#: Delivered evidence the import layer must find, unaltered, before it proceeds.
REQUIRED_BUNDLE_MEMBERS: tuple[str, ...] = (
    BUNDLE_README_REL,
    BUNDLE_REQUEST_REL,
    DAILY_REL,
    MAPPING_REL,
    MANIFEST_REL,
    STATUS_AUDIT_REL,
    RAW_SHA_MANIFEST_REL,
    PROVENANCE_REL,
    EXTERNAL_QC_REL,
)

RAW_DAILY_BASENAME = "closing_price_daily_bounded.json"
RAW_ADJUSTED_BASENAME = "adjusted_price_history_bounded.csv"

#: The delivery must NOT carry the external programmer's full-history escrow.
FORBIDDEN_PREFIX = f"{ROOT}/raw_full_escrow/"

# --------------------------------------------------------------------------- #
# Expected shape, declared independently of the delivered QC report
# --------------------------------------------------------------------------- #

EXPECTED_TICKERS = 110
EXPECTED_RANGES = 111
EXPECTED_MAPPING_ROWS = 110
EXPECTED_MANIFEST_ROWS = 111
EXPECTED_NORMALIZED_ROWS = 163_230
EXPECTED_RESTRICTED_RAW_FILES = 222

EXPECTED_STATUS_COUNTS: dict[str, int] = {
    "SUCCESS": 105,
    "PARTIAL": 6,
    "FAILED": 0,
    "UNRESOLVED_MAPPING": 0,
}

EXPECTED_ADJUSTED_OK = 135_615
EXPECTED_ADJUSTED_UNRESOLVED = 27_615

#: Ranges the external party reported as PARTIAL. They are preserved exactly as
#: delivered: never upgraded to SUCCESS, never back-filled, never widened.
EXPECTED_PARTIAL_RANGES: dict[str, str] = {
    "RNG0008": "ثشرق",
    "RNG0010": "جم",
    "RNG0033": "زپارس",
    "RNG0094": "های وب",
    "RNG0096": "پارس",
    "RNG0109": "کویر",
}

ADJUSTED_STATUS_OK = "OK"
ADJUSTED_STATUS_UNRESOLVED = "ADJUSTED_CLOSE_UNRESOLVED"

ALLOWED_RETRIEVAL_STATUS = tuple(EXPECTED_STATUS_COUNTS)

#: The only endpoints any provenance record may cite. TSETMC only.
ALLOWED_ENDPOINT_HOSTS: tuple[str, ...] = (
    "cdn.tsetmc.com",
    "members.tsetmc.com",
    "www.tsetmc.com",
    "old.tsetmc.com",
    "tsetmc.com",
)

DAILY_ENDPOINT_MARKER = "cdn.tsetmc.com/api/ClosingPrice/GetClosingPriceDailyList"
ADJUSTED_ENDPOINT_MARKER = (
    "members.tsetmc.com/tsev2/chart/data/Financial.aspx"
)

#: Frozen raw -> normalized field mapping. Verified for EVERY row, not a sample.
RAW_TO_NORMALIZED: tuple[tuple[str, str], ...] = (
    ("pClosing", "raw_close"),
    ("pDrCotVal", "last_price"),
    ("priceFirst", "open"),
    ("priceMax", "high"),
    ("priceMin", "low"),
    ("qTotCap", "traded_value_rial"),
    ("qTotCap", "raw_traded_value"),
    ("qTotTran5J", "volume"),
    ("zTotTran", "trade_count"),
)

REQUIRED_TRADED_VALUE_UNIT = "rial"

#: Position of the adjusted closing price ``pc`` inside a Financial.aspx
#: ``t=ph&a=1`` record: dEven, priceMax, priceMin, priceFirst, last, volume, pc.
ADJUSTED_FIELD_COUNT = 7
ADJUSTED_PC_INDEX = 6
ADJUSTED_VOLUME_INDEX = 5

#: Final-test firewall, enforced on imported dates regardless of what a future
#: bundle claims. No development pair cutoff can reach this date.
FINAL_TEST_FIREWALL_MIN_EXCLUDED_DATE = "2020-07-19"

#: Non-blocking sanity diagnostic: implied VWAP = qTotCap / qTotTran5J should sit
#: inside the raw [priceMin, priceMax] band. Sub-rounding excursions are recorded,
#: never repaired.
VWAP_BAND_RELATIVE_TOLERANCE = 1e-9
VWAP_BAND_MATERIAL_RELATIVE_DEVIATION = 0.01


class ImportFail(Exception):
    """Raised when imported evidence fails any fail-closed validation."""


# --------------------------------------------------------------------------- #
# Small helpers
# --------------------------------------------------------------------------- #

def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _read_csv(data: bytes) -> list[dict[str, str]]:
    text = data.decode("utf-8-sig")
    return list(csv.DictReader(io.StringIO(text)))


def _num(value: str) -> float | None:
    v = (value or "").strip()
    if v == "":
        return None
    return float(v)


def deven_to_iso(deven: int) -> str:
    s = str(int(deven))
    if len(s) != 8:
        raise ImportFail(f"malformed dEven: {deven}")
    return f"{s[0:4]}-{s[4:6]}-{s[6:8]}"


def parse_adjusted_records(text: str) -> dict[str, float]:
    """Parse a Financial.aspx ``t=ph&a=1`` payload into {iso_date: pc}.

    Parsed independently of the external extraction code so a defect there
    cannot propagate silently into the Gate.
    """
    out: dict[str, float] = {}
    for part in text.strip().split(";"):
        if not part.strip():
            continue
        fields = part.split(",")
        if len(fields) < ADJUSTED_FIELD_COUNT:
            raise ImportFail(f"malformed adjusted record: {part!r}")
        iso = deven_to_iso(int(fields[0]))
        if iso in out:
            raise ImportFail(f"duplicate adjusted date {iso}")
        out[iso] = float(fields[ADJUSTED_PC_INDEX])
    return out


def parse_adjusted_volumes(text: str) -> dict[str, float]:
    """Volume column of the adjusted payload, used only as a join cross-check."""
    out: dict[str, float] = {}
    for part in text.strip().split(";"):
        if not part.strip():
            continue
        fields = part.split(",")
        if len(fields) < ADJUSTED_FIELD_COUNT:
            continue
        out[deven_to_iso(int(fields[0]))] = float(fields[ADJUSTED_VOLUME_INDEX])
    return out


# --------------------------------------------------------------------------- #
# Immutable bundle handle
# --------------------------------------------------------------------------- #

class ExternalDelivery:
    """Read-only handle over the external ZIP. Nothing is ever written back."""

    def __init__(self, zip_path: str, *, expected_sha256: str | None = None,
                 expected_size: int | None = None) -> None:
        self.zip_path = os.path.abspath(zip_path)
        if not os.path.isfile(self.zip_path):
            raise ImportFail(f"external bundle not found: {self.zip_path}")

        self.size_bytes = os.path.getsize(self.zip_path)
        self.sha256 = sha256_file(self.zip_path)

        want_sha = BUNDLE_SHA256 if expected_sha256 is None else expected_sha256
        want_size = BUNDLE_SIZE_BYTES if expected_size is None else expected_size

        if self.size_bytes != want_size:
            raise ImportFail(
                f"external bundle size mismatch: expected {want_size}, "
                f"got {self.size_bytes}"
            )
        if self.sha256 != want_sha:
            raise ImportFail(
                f"external bundle SHA256 mismatch: expected {want_sha}, "
                f"got {self.sha256}"
            )

        self._zf = zipfile.ZipFile(self.zip_path)
        self.names = tuple(self._zf.namelist())

        for name in self.names:
            if name.startswith(FORBIDDEN_PREFIX):
                raise ImportFail(
                    "delivery contains raw_full_escrow; the full-history escrow "
                    "must remain outside the ingested evidence bundle"
                )
        for required in REQUIRED_BUNDLE_MEMBERS:
            if required not in self.names:
                raise ImportFail(f"delivery is missing required member: {required}")

    def close(self) -> None:
        self._zf.close()

    def __enter__(self) -> "ExternalDelivery":
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()

    def read(self, member: str) -> bytes:
        try:
            return self._zf.read(member)
        except KeyError as exc:  # pragma: no cover - defensive
            raise ImportFail(f"missing bundle member: {member}") from exc

    def read_text(self, member: str) -> str:
        return self.read(member).decode("utf-8-sig")

    def read_csv(self, member: str) -> list[dict[str, str]]:
        return _read_csv(self.read(member))

    def restricted_files(self) -> list[str]:
        prefix = f"{ROOT}/raw_restricted/"
        return sorted(
            n for n in self.names
            if n.startswith(prefix) and not n.endswith("/")
        )


# --------------------------------------------------------------------------- #
# Canonical request universe
# --------------------------------------------------------------------------- #

def load_canonical_ranges(repo_root: str) -> list[dict[str, str]]:
    path = os.path.join(repo_root, CANONICAL_REQUEST_REL)
    with open(path, "rb") as f:
        data = f.read()
    digest = sha256_bytes(data)
    if digest != CANONICAL_REQUEST_SHA256:
        raise ImportFail(
            "canonical request file in this repository does not match the "
            f"authorized request SHA256 (expected {CANONICAL_REQUEST_SHA256}, "
            f"got {digest})"
        )
    return _read_csv(data)


def verify_delivered_request_matches_canonical(
    delivery: ExternalDelivery, canonical_rows: list[dict[str, str]],
    *, expected_sha256: str | None = None,
) -> dict[str, Any]:
    """The bundle must answer EXACTLY the canonical request, byte for byte."""
    expected = CANONICAL_REQUEST_SHA256 if expected_sha256 is None else expected_sha256
    delivered = delivery.read(BUNDLE_REQUEST_REL)
    digest = sha256_bytes(delivered)
    if digest != expected:
        raise ImportFail(
            "delivered request file does not match the canonical PR #66 "
            f"request (expected {expected}, got {digest}); "
            "a different ticker/range universe is not acceptable"
        )
    delivered_rows = _read_csv(delivered)
    if [r["range_id"] for r in delivered_rows] != [
        r["range_id"] for r in canonical_rows
    ]:
        raise ImportFail("delivered request range_id sequence differs")
    return {
        "delivered_request_sha256": digest,
        "matches_canonical_request": True,
        "canonical_range_count": len(canonical_rows),
        "canonical_ticker_count": len({r["ticker"] for r in canonical_rows}),
    }


# --------------------------------------------------------------------------- #
# Validation
# --------------------------------------------------------------------------- #

def _expect(condition: bool, message: str) -> None:
    if not condition:
        raise ImportFail(message)


def _check_endpoint(endpoint: str, field: str) -> None:
    for chunk in endpoint.split(";"):
        chunk = chunk.strip()
        if not chunk:
            continue
        url = chunk.split()[-1] if " " in chunk else chunk
        if "://" not in url:
            raise ImportFail(f"{field}: non-URL endpoint {chunk!r}")
        host = url.split("://", 1)[1].split("/", 1)[0].lower()
        if host not in ALLOWED_ENDPOINT_HOSTS:
            raise ImportFail(
                f"{field}: non-TSETMC endpoint host {host!r}; only TSETMC is "
                "the authorized source and no substitute is permitted"
            )


def validate_delivery(
    delivery: ExternalDelivery,
    canonical_rows: list[dict[str, str]],
    *,
    expected_normalized_rows: int = EXPECTED_NORMALIZED_ROWS,
    expected_status_counts: dict[str, int] | None = None,
    expected_adjusted_ok: int = EXPECTED_ADJUSTED_OK,
    expected_adjusted_unresolved: int = EXPECTED_ADJUSTED_UNRESOLVED,
    expected_restricted_files: int = EXPECTED_RESTRICTED_RAW_FILES,
    expected_partial_ranges: dict[str, str] | None = None,
    expected_request_sha256: str | None = None,
    strict_expected_counts: bool = True,
) -> tuple[
    dict[str, Any],
    dict[str, list[dict[str, Any]]],
    dict[str, dict[str, str]],
    dict[str, dict[str, str]],
]:
    """Independently revalidate the whole delivery. Fails closed on any mismatch.

    Returns ``(qc, observations_by_ticker, mapping, manifest)``. The QC record is
    derived entirely from the raw evidence; the external
    ``full_extraction_qc_report.json`` is read only so it can be COMPARED, never
    so it can be believed.
    """
    status_targets = (
        dict(EXPECTED_STATUS_COUNTS) if expected_status_counts is None
        else dict(expected_status_counts)
    )
    partial_targets = (
        dict(EXPECTED_PARTIAL_RANGES) if expected_partial_ranges is None
        else dict(expected_partial_ranges)
    )

    request_check = verify_delivered_request_matches_canonical(
        delivery, canonical_rows, expected_sha256=expected_request_sha256
    )

    canonical_by_range = {r["range_id"]: r for r in canonical_rows}
    canonical_tickers = {r["ticker"] for r in canonical_rows}

    # ---------------- mapping: one row per requested ticker ---------------- #
    mapping_rows = delivery.read_csv(MAPPING_REL)
    mapping: dict[str, dict[str, str]] = {}
    for r in mapping_rows:
        t = r["requested_ticker"]
        _expect(t not in mapping, f"mapping has duplicate ticker row: {t}")
        _expect(
            t in canonical_tickers,
            f"mapping contains ticker outside canonical development scope: {t}",
        )
        _expect(
            r["mapping_status"] == "MATCHED",
            f"ticker {t} mapping_status={r['mapping_status']!r}; unresolved "
            "mapping is never guessed and cannot be admitted",
        )
        _expect(bool(r["tsetmc_instrument_id"].strip()), f"{t}: empty InsCode")
        _expect(bool(r["isin"].strip()), f"{t}: empty ISIN")
        mapping[t] = r
    _expect(
        set(mapping) == canonical_tickers,
        "mapping tickers differ from the canonical requested ticker universe",
    )
    if strict_expected_counts:
        _expect(
            len(mapping_rows) == EXPECTED_MAPPING_ROWS,
            f"expected {EXPECTED_MAPPING_ROWS} mapping rows, "
            f"got {len(mapping_rows)}",
        )

    # ---------------- manifest: one row per authorized range --------------- #
    manifest_rows = delivery.read_csv(MANIFEST_REL)
    manifest: dict[str, dict[str, str]] = {}
    status_counts = {s: 0 for s in ALLOWED_RETRIEVAL_STATUS}
    for r in manifest_rows:
        rid = r["range_id"]
        _expect(rid not in manifest, f"duplicate range_id in manifest: {rid}")
        _expect(rid in canonical_by_range, f"manifest has extra range_id: {rid}")
        canon = canonical_by_range[rid]
        _expect(
            r["requested_ticker"] == canon["ticker"],
            f"{rid}: manifest ticker {r['requested_ticker']!r} != canonical "
            f"{canon['ticker']!r}",
        )
        _expect(
            r["requested_start_date"] == canon["requested_start_date"]
            and r["requested_end_date"] == canon["requested_end_date"],
            f"{rid}: delivered range differs from the authorized range; the "
            "retrieval period must never be widened or shifted",
        )
        _expect(
            r["retrieval_status"] in ALLOWED_RETRIEVAL_STATUS,
            f"{rid}: unknown retrieval_status {r['retrieval_status']!r}",
        )
        _expect(
            r["tsetmc_instrument_id"] == mapping[canon["ticker"]][
                "tsetmc_instrument_id"
            ],
            f"{rid}: manifest InsCode disagrees with the mapping row",
        )
        _check_endpoint(r["source_endpoint"], f"{rid} manifest source_endpoint")
        status_counts[r["retrieval_status"]] += 1
        manifest[rid] = r

    missing = sorted(set(canonical_by_range) - set(manifest))
    _expect(not missing, f"manifest is missing range_id(s): {missing}")
    if strict_expected_counts:
        _expect(
            len(manifest_rows) == EXPECTED_MANIFEST_ROWS,
            f"expected {EXPECTED_MANIFEST_ROWS} manifest rows, "
            f"got {len(manifest_rows)}",
        )
        _expect(
            status_counts == status_targets,
            f"retrieval status counts {status_counts} != expected "
            f"{status_targets}",
        )

    observed_partial = {
        rid: r["requested_ticker"]
        for rid, r in manifest.items() if r["retrieval_status"] == "PARTIAL"
    }
    if strict_expected_counts:
        _expect(
            observed_partial == partial_targets,
            f"PARTIAL ranges {observed_partial} differ from the delivered "
            f"evidence {partial_targets}; PARTIAL ranges are preserved as "
            "delivered and are never upgraded to improve coverage",
        )

    # ---------------- restricted raw hashes -------------------------------- #
    raw_sha_rows = delivery.read_csv(RAW_SHA_MANIFEST_REL)
    raw_sha_manifest = {r["file"]: r["sha256"] for r in raw_sha_rows}
    _expect(
        len(raw_sha_manifest) == len(raw_sha_rows),
        "raw SHA manifest contains duplicate file entries",
    )

    restricted_members = delivery.restricted_files()
    if strict_expected_counts:
        _expect(
            len(restricted_members) == expected_restricted_files,
            f"expected {expected_restricted_files} restricted raw files, "
            f"got {len(restricted_members)}",
        )

    raw_bytes: dict[str, bytes] = {}
    verified_hashes = 0
    for member in restricted_members:
        rel = member[len(f"{ROOT}/"):]
        data = delivery.read(member)
        raw_bytes[rel] = data
        _expect(rel in raw_sha_manifest, f"raw file not in SHA manifest: {rel}")
        digest = sha256_bytes(data)
        _expect(
            digest == raw_sha_manifest[rel],
            f"restricted raw SHA256 mismatch for {rel}: manifest "
            f"{raw_sha_manifest[rel]}, computed {digest}",
        )
        verified_hashes += 1
    _expect(
        set(raw_sha_manifest) == set(raw_bytes),
        "raw SHA manifest and delivered restricted files do not correspond",
    )

    # ---------------- provenance cross-check ------------------------------- #
    provenance_rows = delivery.read_csv(PROVENANCE_REL)
    _expect(
        len(provenance_rows) == len(restricted_members),
        f"provenance manifest has {len(provenance_rows)} rows for "
        f"{len(restricted_members)} restricted raw files",
    )
    provenance_by_file: dict[str, dict[str, str]] = {}
    for r in provenance_rows:
        rel = r["restricted_raw_file"]
        _expect(rel not in provenance_by_file, f"duplicate provenance row {rel}")
        _expect(rel in raw_bytes, f"provenance references unknown file {rel}")
        _expect(
            r["restricted_raw_sha256"] == raw_sha_manifest[rel],
            f"provenance SHA disagrees with raw_sha256_manifest for {rel}",
        )
        rid = r["range_id"]
        _expect(rid in manifest, f"provenance references unknown range {rid}")
        _expect(
            r["InsCode"] == manifest[rid]["tsetmc_instrument_id"],
            f"{rid}: provenance InsCode disagrees with the manifest",
        )
        _expect(
            r["requested_start_date"] == canonical_by_range[rid][
                "requested_start_date"
            ]
            and r["requested_end_date"] == canonical_by_range[rid][
                "requested_end_date"
            ],
            f"{rid}: provenance range differs from the authorized range",
        )
        _check_endpoint(r["source_endpoint"], f"{rid} provenance source_endpoint")
        provenance_by_file[rel] = r

    # ---------------- raw evidence, parsed independently ------------------- #
    raw_daily: dict[str, dict[str, dict[str, Any]]] = {}
    raw_adjusted: dict[str, dict[str, float]] = {}
    raw_adjusted_volume: dict[str, dict[str, float]] = {}
    raw_date_violations: list[str] = []

    for rid, mrow in manifest.items():
        canon = canonical_by_range[rid]
        lo, hi = canon["requested_start_date"], canon["requested_end_date"]

        daily_rel = f"raw_restricted/{rid}/{RAW_DAILY_BASENAME}"
        adj_rel = f"raw_restricted/{rid}/{RAW_ADJUSTED_BASENAME}"
        _expect(daily_rel in raw_bytes, f"{rid}: missing {RAW_DAILY_BASENAME}")
        _expect(adj_rel in raw_bytes, f"{rid}: missing {RAW_ADJUSTED_BASENAME}")

        payload = json.loads(raw_bytes[daily_rel].decode("utf-8"))
        records = payload["closingPriceDaily"]
        by_date: dict[str, dict[str, Any]] = {}
        for rec in records:
            iso = deven_to_iso(rec["dEven"])
            _expect(iso not in by_date, f"{rid}: duplicate raw date {iso}")
            if not (lo <= iso <= hi):
                raw_date_violations.append(f"{rid}:{iso}")
            _expect(
                str(rec["insCode"]) == mrow["tsetmc_instrument_id"],
                f"{rid}: raw insCode disagrees with the mapped instrument",
            )
            by_date[iso] = rec
        raw_daily[rid] = by_date

        adj_text = raw_bytes[adj_rel].decode("utf-8")
        adjusted = parse_adjusted_records(adj_text)
        for iso in adjusted:
            if not (lo <= iso <= hi):
                raw_date_violations.append(f"{rid}:adjusted:{iso}")
        raw_adjusted[rid] = adjusted
        raw_adjusted_volume[rid] = parse_adjusted_volumes(adj_text)

    _expect(
        not raw_date_violations,
        "restricted raw evidence contains dates outside the authorized range: "
        f"{raw_date_violations[:10]}",
    )

    # ---------------- normalized rows, revalidated against raw ------------- #
    normalized_rows = delivery.read_csv(DAILY_REL)
    if strict_expected_counts:
        _expect(
            len(normalized_rows) == expected_normalized_rows,
            f"expected {expected_normalized_rows} normalized rows, "
            f"got {len(normalized_rows)}",
        )

    # range lookup per (ticker, date): a ticker may own several disjoint ranges
    range_ids_by_ticker: dict[str, list[str]] = {}
    for rid, canon in canonical_by_range.items():
        range_ids_by_ticker.setdefault(canon["ticker"], []).append(rid)

    seen_keys: set[tuple[str, str]] = set()
    adjusted_ok = 0
    adjusted_unresolved = 0
    zero_traded_value = 0
    positive_traded_value = 0
    unresolved_with_zero_value = 0
    positive_value_with_adjusted = 0
    field_mismatches: list[str] = []
    adjusted_mismatches: list[str] = []
    vwap_violations: list[dict[str, Any]] = []
    normalized_min_date = "9999-12-31"
    normalized_max_date = "0001-01-01"
    observations: dict[str, list[dict[str, Any]]] = {}

    for row in normalized_rows:
        ticker = row["requested_ticker"]
        iso = row["trading_date"]
        key = (ticker, iso)
        _expect(
            key not in seen_keys,
            f"duplicate normalized key requested_ticker/trading_date: {key}",
        )
        seen_keys.add(key)
        _expect(
            ticker in canonical_tickers,
            f"normalized row for ticker outside canonical scope: {ticker}",
        )
        _expect(
            iso < FINAL_TEST_FIREWALL_MIN_EXCLUDED_DATE,
            f"final-test firewall violation: imported observation {ticker} "
            f"{iso} is at or beyond {FINAL_TEST_FIREWALL_MIN_EXCLUDED_DATE}",
        )
        mrow = mapping[ticker]
        _expect(
            row["tsetmc_instrument_id"] == mrow["tsetmc_instrument_id"],
            f"{key}: InsCode disagrees with the mapping",
        )
        _expect(row["isin"] == mrow["isin"], f"{key}: ISIN disagrees with mapping")
        _expect(
            row["ticker"] == mrow["matched_ticker"],
            f"{key}: matched ticker disagrees with the mapping",
        )
        _expect(
            row["raw_traded_value_unit"] == REQUIRED_TRADED_VALUE_UNIT,
            f"{key}: raw_traded_value_unit={row['raw_traded_value_unit']!r}",
        )
        _check_endpoint(row["source_endpoint"], f"{key} source_endpoint")
        _expect(
            DAILY_ENDPOINT_MARKER in row["source_endpoint"]
            and ADJUSTED_ENDPOINT_MARKER in row["source_endpoint"],
            f"{key}: source_endpoint does not cite both TSETMC endpoints",
        )

        owning = [
            rid for rid in range_ids_by_ticker[ticker]
            if canonical_by_range[rid]["requested_start_date"] <= iso
            <= canonical_by_range[rid]["requested_end_date"]
        ]
        _expect(
            len(owning) == 1,
            f"{key}: observation does not lie in exactly one authorized range "
            f"(matched {owning})",
        )
        rid = owning[0]
        _expect(
            f"raw_restricted/{rid}/" in row["raw_response_file"],
            f"{key}: raw_response_file does not point at range {rid}",
        )
        for rel_part, sha_part in zip(
            [p.strip() for p in row["raw_response_file"].split(";")],
            [p.strip() for p in row["raw_response_sha256"].split(";")],
        ):
            _expect(
                raw_sha_manifest.get(rel_part) == sha_part,
                f"{key}: raw_response_sha256 disagrees with the raw manifest "
                f"for {rel_part}",
            )

        raw = raw_daily[rid].get(iso)
        _expect(
            raw is not None,
            f"{key}: normalized row has no corresponding raw observation in "
            f"{rid}",
        )
        for raw_field, norm_field in RAW_TO_NORMALIZED:
            expected = float(raw[raw_field])
            got = _num(row[norm_field])
            if got is None or got != expected:
                field_mismatches.append(
                    f"{key}: {raw_field}->{norm_field} raw={expected} "
                    f"normalized={row[norm_field]!r}"
                )

        status = row["adjusted_close_status"]
        adj_value = _num(row["adjusted_close"])
        raw_pc = raw_adjusted[rid].get(iso)
        if status == ADJUSTED_STATUS_OK:
            adjusted_ok += 1
            if raw_pc is None:
                adjusted_mismatches.append(f"{key}: status OK but no raw pc")
            elif adj_value is None or adj_value != raw_pc:
                adjusted_mismatches.append(
                    f"{key}: adjusted_close={row['adjusted_close']!r} != raw "
                    f"pc={raw_pc} on the same trading date"
                )
        elif status == ADJUSTED_STATUS_UNRESOLVED:
            adjusted_unresolved += 1
            if adj_value is not None:
                adjusted_mismatches.append(
                    f"{key}: UNRESOLVED status must carry an empty "
                    "adjusted_close; raw_close is never substituted"
                )
            if raw_pc is not None:
                adjusted_mismatches.append(
                    f"{key}: marked UNRESOLVED although raw pc exists"
                )
        else:
            raise ImportFail(f"{key}: unknown adjusted_close_status {status!r}")

        value = float(raw["qTotCap"])
        volume = float(raw["qTotTran5J"])
        if value > 0:
            positive_traded_value += 1
            if status == ADJUSTED_STATUS_OK:
                positive_value_with_adjusted += 1
        else:
            zero_traded_value += 1
            if status == ADJUSTED_STATUS_UNRESOLVED:
                unresolved_with_zero_value += 1

        if value > 0 and volume > 0:
            vwap = value / volume
            low = float(raw["priceMin"])
            high = float(raw["priceMax"])
            dev = 0.0
            if low > 0 and vwap < low:
                dev = (low - vwap) / low
            elif high > 0 and vwap > high:
                dev = (vwap - high) / high
            if dev > VWAP_BAND_RELATIVE_TOLERANCE:
                vwap_violations.append({
                    "range_id": rid,
                    "requested_ticker": ticker,
                    "trading_date": iso,
                    "implied_vwap": vwap,
                    "raw_price_min": low,
                    "raw_price_max": high,
                    "relative_deviation": dev,
                })

        normalized_min_date = min(normalized_min_date, iso)
        normalized_max_date = max(normalized_max_date, iso)

        observations.setdefault(ticker, []).append({
            "trading_date": iso,
            "range_id": rid,
            "adjusted_close": adj_value,
            "adjusted_close_status": status,
            "traded_value_rial": float(row["traded_value_rial"]),
        })

    _expect(
        not field_mismatches,
        "raw -> normalized field mapping mismatch(es): "
        f"{field_mismatches[:10]} (total {len(field_mismatches)})",
    )
    _expect(
        not adjusted_mismatches,
        "adjusted-close exact-date validation failure(s): "
        f"{adjusted_mismatches[:10]} (total {len(adjusted_mismatches)})",
    )

    if strict_expected_counts:
        _expect(
            adjusted_ok == expected_adjusted_ok,
            f"adjusted_close OK count {adjusted_ok} != "
            f"{expected_adjusted_ok}",
        )
        _expect(
            adjusted_unresolved == expected_adjusted_unresolved,
            f"adjusted_close UNRESOLVED count {adjusted_unresolved} != "
            f"{expected_adjusted_unresolved}",
        )

    for ticker in observations:
        observations[ticker].sort(key=lambda o: o["trading_date"])

    material_vwap = [
        v for v in vwap_violations
        if v["relative_deviation"] > VWAP_BAND_MATERIAL_RELATIVE_DEVIATION
    ]

    external_qc = json.loads(delivery.read_text(EXTERNAL_QC_REL))

    qc: dict[str, Any] = {
        "bundle_filename": BUNDLE_FILENAME,
        "bundle_sha256": delivery.sha256,
        "bundle_size_bytes": delivery.size_bytes,
        "bundle_sha256_verified": True,
        "raw_full_escrow_present_in_delivery": False,
        "canonical_request_check": request_check,
        "expected_ticker_count": EXPECTED_TICKERS,
        "expected_range_count": EXPECTED_RANGES,
        "mapping_rows": len(mapping_rows),
        "manifest_rows": len(manifest_rows),
        "retrieval_status_counts": status_counts,
        "partial_ranges_preserved": observed_partial,
        "partial_ranges_upgraded_to_success": 0,
        "missing_range_ids": [],
        "extra_range_ids": [],
        "duplicate_range_ids": 0,
        "restricted_raw_file_count": len(restricted_members),
        "restricted_raw_hashes_verified": verified_hashes,
        "restricted_raw_hash_verification_passed": True,
        "provenance_rows": len(provenance_rows),
        "provenance_sha_agrees_with_raw_manifest": True,
        "normalized_row_count": len(normalized_rows),
        "duplicate_normalized_key_count": 0,
        "normalized_min_trading_date": normalized_min_date,
        "normalized_max_trading_date": normalized_max_date,
        "all_restricted_dates_within_authorized_ranges": True,
        "all_normalized_dates_within_authorized_ranges": True,
        "raw_to_normalized_field_mapping_verified_rows": len(normalized_rows),
        "raw_to_normalized_field_mismatches": 0,
        "raw_to_normalized_field_map": {
            f"{raw}->{norm}": "verified" for raw, norm in RAW_TO_NORMALIZED
        },
        "traded_value_recomputed_from_price_times_volume": False,
        "adjusted_close_join_method": "exact_trading_date",
        "adjusted_close_positional_join_used": False,
        "adjusted_close_nearest_or_filled_join_used": False,
        "adjusted_close_ok_count": adjusted_ok,
        "adjusted_close_unresolved_count": adjusted_unresolved,
        "adjusted_close_exact_date_mismatches": 0,
        "raw_close_substituted_for_adjusted_close": False,
        "traded_value_rial_positive_count": positive_traded_value,
        "traded_value_rial_zero_count": zero_traded_value,
        "observed_property_unresolved_rows_all_zero_traded_value": (
            unresolved_with_zero_value == adjusted_unresolved
        ),
        "observed_property_positive_value_rows_all_have_adjusted_close": (
            positive_value_with_adjusted == positive_traded_value
        ),
        "observed_property_is_not_a_scientific_rule": True,
        "imputation_or_synthetic_values_introduced": False,
        "source_endpoints_tsetmc_only": True,
        "requested_ticker_preserved_separately_from_matched_ticker": True,
        "final_test_firewall_min_excluded_date": (
            FINAL_TEST_FIREWALL_MIN_EXCLUDED_DATE
        ),
        "final_test_period_observations_imported": 0,
        "vwap_band_diagnostic": {
            "is_blocking": False,
            "rule": "qTotCap / qTotTran5J within raw [priceMin, priceMax]",
            "violation_count": len(vwap_violations),
            "max_relative_deviation": (
                max(v["relative_deviation"] for v in vwap_violations)
                if vwap_violations else 0.0
            ),
            "material_violation_count": len(material_vwap),
            "material_threshold_relative": (
                VWAP_BAND_MATERIAL_RELATIVE_DEVIATION
            ),
            "violations": vwap_violations,
            "source_data_mutated": False,
        },
        "external_qc_report_trusted": False,
        "external_qc_report_as_delivered": external_qc,
        "independent_validation_passed": True,
    }
    return qc, observations, mapping, manifest


def observations_by_ticker(
    delivery: ExternalDelivery, repo_root: str,
) -> tuple[dict[str, Any], dict[str, list[dict[str, Any]]]]:
    """Convenience wrapper: validate then return (qc, observations)."""
    canonical = load_canonical_ranges(repo_root)
    qc, obs, _mapping, _manifest = validate_delivery(delivery, canonical)
    return qc, obs


def _iter_files(paths: Iterable[str]) -> list[str]:  # pragma: no cover - helper
    return sorted(paths)


__all__ = [
    "ExternalDelivery",
    "ImportFail",
    "load_canonical_ranges",
    "validate_delivery",
    "observations_by_ticker",
    "parse_adjusted_records",
    "deven_to_iso",
    "sha256_bytes",
    "sha256_file",
]
